"""squeeze-kernel 2.0: SqueezeKernel API + cross-engine goldens.

The golden file was generated by the research engine (squeeze_cov branch
v2, experiments/v2/variants.py::v2_series) under the frozen v2
configuration on a synthetic one-factor panel with late listings and
MCAR missing values.  The library must reproduce the per-day one-step
NLL path for all three switch combinations.
"""
from pathlib import Path

import numpy as np
import pytest

from squeeze_kernel import CONSTANTS, SqueezeKernel, SqueezeKernelEstimator

GOLDEN = Path(__file__).parent / "golden" / "v2_selftuning.npz"


def _make_spd(cov, eps=1e-8):
    cov = (cov + cov.T) * 0.5
    min_eig = float(np.linalg.eigvalsh(cov).min())
    if min_eig < eps:
        cov = cov + np.eye(cov.shape[0]) * (eps - min_eig)
    return cov


def _nll(cov, r):
    sign, logdet = np.linalg.slogdet(cov)
    if sign <= 0:
        return float("nan")
    return float(logdet + r @ np.linalg.solve(cov, r))


def _v2_estimator(n, **overrides):
    """The SqueezeKernel default configuration at estimator level, with
    ablation overrides (the 2.0 public class has no switches)."""
    kw = dict(lambda_vol=CONSTANTS.lambda_vol, shrinkage="auto",
              shrinkage_target="cluster",
              corr_half_lives=(173.0 / CONSTANTS.b, 173.0,
                               173.0 * CONSTANTS.b),
              corr_theta=CONSTANTS.theta, kappa_mode="adaptive",
              alpha_rule="selftuning", level_match=False, detector=True,
              clock="asset", epsilon=CONSTANTS.epsilon)
    kw.update(overrides)
    return SqueezeKernelEstimator(n, **kw)


def _nll_path(est_factory, X, eval_start):
    est = None
    out = []
    for t in range(X.shape[0] - 1):
        if est is None:
            est = est_factory(X.shape[1])
        est.update(X[t])
        if t >= eval_start:
            rn = X[t + 1]
            out.append(_nll(_make_spd(est.get_cov()), rn)
                       if np.isfinite(rn).all() else np.nan)
    return np.asarray(out)


def _library_nll_path(X, eval_start, **kw):
    sk = SqueezeKernel(**kw)
    out = []
    for t in range(X.shape[0] - 1):
        sk.update(X[t])
        if t >= eval_start:
            rn = X[t + 1]
            out.append(_nll(_make_spd(sk.covariance()), rn)
                       if np.isfinite(rn).all() else np.nan)
    return np.asarray(out)


@pytest.fixture(scope="module")
def golden():
    d = np.load(GOLDEN)
    return d["X"], int(d["eval_start"][0]), d


def test_public_class_matches_research_engine(golden):
    X, es, d = golden
    nll = _library_nll_path(X, es, half_life=173.0)
    ref = d["nll_full"]
    both = np.isfinite(nll) & np.isfinite(ref)
    assert (np.isfinite(nll) == np.isfinite(ref)).all()
    dmax = float(np.max(np.abs(nll[both] - ref[both])))
    assert dmax < 1e-8, f"public class: max per-day NLL drift {dmax:.2e}"


@pytest.mark.parametrize("name,over", [
    ("equi", dict(shrinkage_target="equicorrelation")),
    ("nodet", dict(detector=False)),
    ("globalclock", dict(clock="global")),
])
def test_matches_research_engine(golden, name, over):
    X, es, d = golden
    nll = _nll_path(lambda n: _v2_estimator(n, **over), X, es)
    ref = d[f"nll_{name}"]
    assert nll.shape == ref.shape
    both = np.isfinite(nll) & np.isfinite(ref)
    assert (np.isfinite(nll) == np.isfinite(ref)).all()
    dmax = float(np.max(np.abs(nll[both] - ref[both])))
    assert dmax < 1e-8, f"{name}: max per-day NLL drift {dmax:.2e}"


def test_derived_ladder():
    sk = SqueezeKernel(half_life=173.0)
    est = sk._build(5)
    assert tuple(est.corr_half_lives) == (43.25, 173.0, 692.0)
    assert est.corr_theta == CONSTANTS.theta == 0.5
    assert est.clock == "asset"


def test_asset_clocks_differentiate():
    # two independent blocks; shock only block A: A's clocks must run
    # ahead of B's
    rng = np.random.default_rng(9)
    n = 12
    X = rng.standard_normal((224, n)) * 0.01
    X[:, :6] += np.outer(rng.standard_normal(224) * 0.01, np.ones(6))
    X[200:, :6] *= 6.0                          # block-A stress to the end
    sk = SqueezeKernel()
    for r in X:
        sk.update(r)
    S_a = sk._est._S_asset                      # fast rung, at stress end
    assert S_a is not None
    assert S_a[0, :6].mean() > S_a[0, 6:].mean()


def test_lazy_n_and_mask():
    rng = np.random.default_rng(0)
    sk = SqueezeKernel()
    r = rng.normal(0, 0.01, 8)
    sk.update(r, mask=np.ones(8, bool))
    assert sk.state()["n_assets"] == 8
    m = np.ones(8, bool); m[2] = False
    sk.update(r, mask=m)
    cov = sk.covariance()
    assert cov.shape == (8, 8) and np.isfinite(cov).all()


def test_psd_along_path():
    rng = np.random.default_rng(1)
    sk = SqueezeKernel()
    for t, r in enumerate(rng.standard_t(5, size=(400, 15)) * 0.01):
        if t % 7 == 0:
            r[t % 15] = np.nan
        sk.update(r)
        if t % 50 == 49:
            ev = np.linalg.eigvalsh(sk.covariance())
            assert ev.min() > -1e-10


def test_state_diagnostics():
    rng = np.random.default_rng(2)
    sk = SqueezeKernel()
    for r in rng.normal(0, 0.01, size=(120, 10)):
        sk.update(r)
    st = sk.state()
    assert st["t"] == 120 and st["n_assets"] == 10
    assert len(st["rung_nu"]) == 3 and st["rung_nu"][0] > 1
    assert 0.0 < st["kappa_t"] < 2.0


def test_no_public_switches():
    import inspect
    sig = inspect.signature(SqueezeKernel.__init__)
    assert list(sig.parameters) == ["self", "half_life"]


def test_v1_escape_hatch():
    est = SqueezeKernel.v1(4, lambda_vol=0.98, kappa=0.25)
    assert isinstance(est, SqueezeKernelEstimator)
    est.update(np.array([0.01, -0.02, 0.0, 0.005]))
    assert est.get_cov().shape == (4, 4)


def test_defaults_do_not_touch_v1():
    # the v2 opt-ins must be inert on a default v1 estimator
    rng = np.random.default_rng(4)
    X = rng.normal(0, 0.01, size=(200, 6))
    a = SqueezeKernelEstimator(6)
    b = SqueezeKernelEstimator(6, kappa_mode="fixed", alpha_rule="published",
                               level_match=True, detector=True)
    for r in X:
        a.update(r); b.update(r)
    assert np.array_equal(a.get_cov(), b.get_cov())


def test_selftuning_target_variant_runs_and_differs():
    rng = np.random.default_rng(5)
    # sign-symmetric block structure: the corner the target-family fit closes
    n = 20
    C = np.full((n, n), -0.15)
    for b in range(4):
        C[b*5:(b+1)*5, b*5:(b+1)*5] = 0.5
    np.fill_diagonal(C, 1.0)
    L = np.linalg.cholesky(C + 1e-10*np.eye(n))
    X = (rng.standard_normal((400, n)) @ L.T) * 0.01
    covs = {}
    for rule in ("selftuning", "selftuning-target"):
        est = SqueezeKernelEstimator(
            n, lambda_vol=0.98, shrinkage="auto", shrinkage_target="cluster",
            corr_half_lives=(43., 173., 693.), corr_theta=0.5,
            kappa_mode="adaptive", alpha_rule=rule, level_match=False)
        for r in X:
            est.update(r)
        covs[rule] = est.get_cov()
    assert not np.allclose(covs["selftuning"], covs["selftuning-target"])
    for c in covs.values():
        assert np.linalg.eigvalsh(c).min() > -1e-10
